inherit_from: .rubocop_todo.yml

require: rubocop-performance

# inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  CacheRootDirectory: tmp
  MaxFilesInCache: 25000
  NewCops: enable

Layout/LineLength:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/RegexpLiteral:
  Enabled: true
  EnforcedStyle: mixed

Performance/Sum: # (new in 1.8)
  Enabled: true

Performance/ReverseFirst: # (new in 1.7)
  Enabled: true

Performance/SortReverse: # (new in 1.7)
  Enabled: true

Performance/Squeeze: # (new in 1.7)
  Enabled: true

Performance/StringInclude: # (new in 1.7)
  Enabled: true

Performance/MethodObjectAsBlock: # (new in 1.9)
  Enabled: true

Performance/RedundantEqualityComparisonBlock: # (new in 1.10)
  Enabled: true

Performance/RedundantSortBlock: # (new in 1.7)
  Enabled: true

Performance/RedundantSplitRegexpArgument: # (new in 1.10)
  Enabled: true

Performance/RedundantStringChars: # (new in 1.7)
  Enabled: true

Performance/AncestorsInclude: # (new in 1.7)
  Enabled: true

Performance/BigDecimalWithNumericArgument: # (new in 1.7)
  Enabled: true

Performance/BlockGivenWithExplicitBlock: # (new in 1.9)
  Enabled: true

Performance/CollectionLiteralInLoop: # (new in 1.8)
  Enabled: true

Performance/ConstantRegexp: # (new in 1.9)
  Enabled: true

Layout/BeginEndAlignment: # (new in 0.91)
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor: # (new in 0.83)
  Enabled: true

Layout/SpaceAroundMethodCallOperator: # (new in 0.82)
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands: # (new in 0.89)
  Enabled: true

Lint/ConstantDefinitionInBlock: # (new in 0.91)
  Enabled: true

Lint/DeprecatedOpenSSLConstant: # (new in 0.84)
  Enabled: true

Lint/DuplicateElsifCondition: # (new in 0.88)
  Enabled: true

Lint/DuplicateRequire: # (new in 0.90)
  Enabled: true

Lint/DuplicateRescueException: # (new in 0.89)
  Enabled: true

Lint/EmptyConditionalBody: # (new in 0.89)
  Enabled: true

Lint/EmptyFile: # (new in 0.90)
  Enabled: true

Lint/FloatComparison: # (new in 0.89)
  Enabled: true

Lint/HashCompareByIdentity: # (new in 0.93)
  Enabled: true

Lint/IdentityComparison: # (new in 0.91)
  Enabled: true

Lint/MissingSuper: # (new in 0.89)
  Enabled: true

Lint/MixedRegexpCaptureTypes: # (new in 0.85)
  Enabled: true

Lint/OutOfRangeRegexpRef: # (new in 0.89)
  Enabled: true

Lint/RedundantSafeNavigation: # (new in 0.93)
  Enabled: true

Lint/SelfAssignment: # (new in 0.89)
  Enabled: true

Lint/TopLevelReturnWithArgument: # (new in 0.89)
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration: # (new in 0.90)
  Enabled: true

Lint/UnreachableLoop: # (new in 0.89)
  Enabled: true

Lint/UselessMethodDefinition: # (new in 0.90)
  Enabled: true

Lint/UselessTimes: # (new in 0.91)
  Enabled: true

Style/AccessorGrouping: # (new in 0.87)
  Enabled: true

Style/BisectedAttrAccessor: # (new in 0.87)
  Enabled: true

Style/CaseLikeIf: # (new in 0.88)
  Enabled: true

Style/ClassEqualityComparison: # (new in 0.93)
  Enabled: true

Style/CombinableLoops: # (new in 0.90)
  Enabled: true

Style/ExplicitBlockArgument: # (new in 0.89)
  Enabled: false

Style/ExponentialNotation: # (new in 0.82)
  Enabled: true

Style/GlobalStdStream: # (new in 0.89)
  Enabled: true

Style/HashAsLastArrayItem: # (new in 0.88)
  Enabled: true

Style/HashLikeCase: # (new in 0.88)
  Enabled: true

Style/KeywordParametersOrder: # (new in 0.90)
  Enabled: true

# RubyMotion doesn't support standard ruby keyword
# arguments - they are used for the ObjC bridge.
Style/OptionalBooleanParameter: # (new in 0.89)
  Enabled: false

Style/RedundantAssignment: # (new in 0.87)
  Enabled: true

Style/RedundantFetchBlock: # (new in 0.86)
  Enabled: true

Style/RedundantFileExtensionInRequire: # (new in 0.88)
  Enabled: true

Style/RedundantRegexpCharacterClass: # (new in 0.85)
  Enabled: true

# regular expressions are a little squirelly in RubyMotion,
# so let's turn this off
Style/RedundantRegexpEscape: # (new in 0.85)
  Enabled: false

Style/RedundantSelfAssignment: # (new in 0.90)
  Enabled: true

Style/SingleArgumentDig: # (new in 0.89)
  Enabled: true

Style/SlicingWithRange: # (new in 0.83)
  Enabled: false

Style/SoleNestedConditional: # (new in 0.89)
  Enabled: true

# I think there are cases where it's more readable not using
# concatenation.
Style/StringConcatenation: # (new in 0.89)
  Enabled: false
